### ISSUE TITLE
Allow to provide assignee on subtask creation with special syntax

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#15]
* [x] explicitly set assignee by username (syntax `assignee: admin`)
* [x] use the current user (syntax: `assignee: @current`)
* [x] use the assignee of the parent issue (syntax: `assignee: @inherit`)
* [ ] if assignee is mandatory and none is given use project lead

**Comment by codescape** [comment]
For mandatory assignee we can ask the ProjectManager, see:
https://docs.atlassian.com/software/jira/docs/api/7.1.5/com/atlassian/jira/project/ProjectManager.html#getDefaultAssignee-com.atlassian.jira.project.Project-com.atlassian.jira.bc.project.component.ProjectComponent-

**Comment by codescape** [comment]
Handling of mandatory assignee separated into another issue #35.
