### ISSUE TITLE
Extend syntax to allow users to provide estimate on subtask creation

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#18]
**Syntax**

    estimate: 1w 2d 4h 20m

**Tasks**
* [x] ensure correct syntax for estimate
* [x] find out the format of the estimate because the field expects a long value
* [x] persist given estimate in correct format (seconds)

**Comment by codescape** [comment]
It seems like we need to set two fields and the value is set in seconds:

    issue.setOriginalEstimate(3600L) //1h
    issue.setEstimate(3600L)
