### ISSUE TITLE
Test and qualify for Jira Data Center

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#19]
### Documentation
* https://developer.atlassian.com/platform/marketplace/dc-apps-submitting-your-app/
* https://developer.atlassian.com/platform/marketplace/dc-apps-performance-toolkit-user-guide-jira/

### Performance Test Suite
* https://github.com/codescape/dc-app-performance-toolkit

### Ticket
* https://data-center-ecosystem.atlassian.net/servicedesk/customer/portal/3/DCHELP-2712
* https://ecosystem.atlassian.net/servicedesk/customer/portal/34/ECOHELP-6167

### Tasks
- [x] create dependency report
- [x] create security report
- [x] implement app specific performance tests
- [x] create performance report
- [x] create re-index report
- [x] create scale report
- [x] provide everything in the ticket

**Comment by codescape** [comment]
App specific performance tests in separate branch:
https://github.com/codescape/dc-app-performance-toolkit/tree/multiple-subtasks-performance

**Comment by codescape** [comment]
Waiting for response from Atlassian.

**Comment by codescape** [comment]
Approved!
