### ISSUE TITLE
Allow users to create personal subtask templates

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#39]
- [x] create new templates
- [x] see a list of existing templates
- [x] delete existing templates
- [x] allow to choose from existing templates in dialog
