### ISSUE TITLE
Allow project administrators to create subtask templates for projects

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#40]
- [x]  create new templates
- [x]  see a list of existing templates
- [x]  delete existing templates
- [x]  allow to choose from existing templates in dialog

**Comment by codescape** [comment]
closed by 45b9b43597d67b9366fee5532b00b4eb38ef15e6
