### ISSUE TITLE
Allow jira administrators to create global subtask templates for all projects

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#41]
- [ ]  create new templates
- [ ]  see a list of existing templates
- [ ]  delete existing templates
- [ ]  allow to choose from existing templates in dialog

**Comment by codescape** [comment]
Do we really need global templates? I will close this issue and see whether this comes up again.
