### ISSUE TITLE
As a user I want to be able to create longer templates than the current 4000 character limit

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#46]
**Tasks**
- [x] increase the maxmum length of template content
- [x] limit number of templates to 10 per user
- [x] show number of configured templates for user like "Your templates (4 / 10)"

**Considerations**
* Shall we make the maximum number of templates configurable?
* Shall we make the maximum length of templates configurable?

**Comment by codescape** [comment]
configuration will follow if needed
