### ISSUE TITLE
Allow to configure maximum number of templates per user and per project

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#55]
We need to have a global configuration page where we can configure the maximum number of templates per user and the maximum number of templates per project.

**Tasks**

- [x] configuration option for templates per user
- [x] configuration option for templates per project
- [x] REST endpoints for configuration settings to be applied individually
