### ISSUE TITLE
Allow administrators to migrate Quick Subtasks templates

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#74]
As an administrator you should be able to run a migration of all user and project templates from Quick Subtasks for Jira.

- [x] allow to precheck the import
- [x] import user templates
- [x] import project templates
- [x] import only templates that do not yet exist
- [x] transform complex templates into syntax for Multiple Subtasks for Jira

See a draft in https://github.com/codescape/jira-multiple-subtasks/tree/quicksubtasks-migration

**Comment by codescape** [comment]
Consume XML and transform each template into supported format of Multiple Subtasks for Jira.

**Comment by codescape** [comment]
Persist all user templates and project templates but try to avoid duplication? Definition of equality: Transformed template and title are equal.
