### ISSUE TITLE
Add support for @inherit on custom fields

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#79]
Allow to use `@inherit` on all custom fields to inherit the value of the parent issue.

**Tasks**

- [x] implement and test for NUMBER
- [x] implement and test for TEXT
- [x] implement and test for TEXTAREA
- [x] implement and test for RADIO
- [x] implement and test for SELECT
- [x] implement and test for CASCADING_SELECT
- [x] implement and test for MULTISELECT
- [x] implement and test for CHECKBOXES
- [x] implement and test for URL
- [x] implement and test for USER
- [x] implement and test for DATE
- [x] implement and test for DATETIME
- [x] implement and test for LABELS
- [x] documentation
