### ISSUE TITLE
Add support for @inherit in summary to be replaced by the parent summary

### ISSUE THREAD

**Issue by codescape** [codescape/jira-multiple-subtasks#82]
As a user I want to use the parent summary in my subtasks. As an advanced user I want to be able to escape `@inherit` so that it is not replaced by the parent summary.

**Examples**

positive examples:

    - Use the parent text here: @inherit
    - Test @inherit
    - Implement @inherit

negative examples:

    - Do not use the parent text here: \@inherit

**Regular Expression**

This regular expression will only find and replace non-escaped keywords:

    (?<!\\)@inherit

**Tasks**

- [x] implement replacement for `@inherit`
- [x] implement replacement for `\@inherit` to `@inherit`
- [ ] add documentation for syntax
